require "../config"
require "../core/detector"

module Pomtex::Engine
  # Runs a TeX engine with the aril tree mounted into kpathsea's search paths.
  class Runner
    record Result,
      success : Bool,
      exit_code : Int32,
      log : String,
      output : String,
      pdf : Path?,
      elapsed : Time::Span

    getter toolchain : Core::Toolchain
    getter engine : String
    getter source : Path
    getter outdir : Path
    property map_files = [] of String
    property extra_args = [] of String

    def initialize(@toolchain, @engine, source : Path | String, outdir : Path | String? = nil)
      @source = Path[source].expand
      @outdir = outdir ? Path[outdir].expand : @source.parent
    end

    def jobname : String
      File.basename(source.to_s, File.extname(source.to_s))
    end

    def log_path : Path
      outdir.join("#{jobname}.log")
    end

    # The -recorder log: every file the engine read or wrote.
    def fls_path : Path
      outdir.join("#{jobname}.fls")
    end

    # Files the last run read, from the -recorder log.
    def recorded_inputs : Array(Path)
      File.exists?(fls_path) ? self.class.recorded_inputs(File.read(fls_path).scrub) : [] of Path
    end

    # Parses a .fls file into the files that were read but not written. Files
    # the job writes and reads back (.aux, .toc, .out, ...) change on every run;
    # watching them would trigger rebuilds forever.
    def self.recorded_inputs(fls : String) : Array(Path)
      pwd = Path["."]
      inputs = [] of Path
      outputs = Set(Path).new
      fls.each_line(chomp: true) do |line|
        kind, _, file = line.partition(' ')
        next if file.empty?
        case kind
        when "PWD"    then pwd = Path[file]
        when "INPUT"  then inputs << absolute(pwd, file)
        when "OUTPUT" then outputs << absolute(pwd, file)
        end
      end
      inputs.uniq.reject { |path| outputs.includes?(path) }
    end

    # Path#join appends even absolute paths, so absolute entries are kept as-is.
    private def self.absolute(base : Path, file : String) : Path
      path = Path[file]
      (path.absolute? ? path : base.join(path)).normalize
    end

    # Environment for every TeX subprocess (engines and kpsewhich alike).
    #
    # TEXINPUTS gets the aril tree prepended and a trailing ':' so kpathsea still
    # appends its compiled-in defaults; TEXMFAUXTREES exposes the same tree to
    # every other file type (fonts, maps, encodings, bst, lua, ...).
    def self.environment(toolchain : Core::Toolchain) : Hash(String, String)
      texmf = Config.texmf_dir.to_s
      user_inputs = ENV["TEXINPUTS"]?.presence
      inputs = ".:#{texmf}/tex//:"
      inputs = "#{inputs}#{user_inputs}" if user_inputs
      aux = "#{texmf},"
      if (user_aux = ENV["TEXMFAUXTREES"]?.presence)
        aux = "#{aux}#{user_aux}"
      end
      {
        "PATH"            => "#{toolchain.bin_dir}:#{ENV["PATH"]? || "/usr/bin:/bin"}",
        "FONTCONFIG_FILE" => fontconfig_file.to_s,
        "TEXINPUTS"       => inputs,
        "TEXMFAUXTREES"   => aux,
        # Keep log lines unwrapped so missing-file messages parse reliably.
        "max_print_line"  => "10000",
        "error_line"      => "254",
        "half_error_line" => "238",
      }
    end

    def environment : Hash(String, String)
      self.class.environment(toolchain)
    end

    # XeTeX finds fonts *by name* only through fontconfig, so pomtex keeps its own
    # fonts.conf: the user's/system configuration plus the aril and rind font
    # directories (fontconfig skips directories that do not exist).
    def self.fontconfig_file : Path
      conf = Config.cache_root.join("fonts.conf")
      texmf = Config.texmf_dir
      base = ENV["FONTCONFIG_FILE"]?.presence || "/etc/fonts/fonts.conf"
      xml = <<-XML
        <?xml version="1.0"?>
        <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
        <!-- generated by pomtex; rewritten when needed -->
        <fontconfig>
          <include ignore_missing="yes">#{base}</include>
          <dir>#{texmf.join("fonts", "opentype")}</dir>
          <dir>#{texmf.join("fonts", "truetype")}</dir>
          <dir>#{Config.rind_dir.join("texmf-dist", "fonts", "opentype")}</dir>
          <dir>#{Config.rind_dir.join("texmf-dist", "fonts", "truetype")}</dir>
          <cachedir>#{Config.cache_root.join("fontconfig")}</cachedir>
        </fontconfig>

        XML
      unless File.exists?(conf) && File.read(conf) == xml
        Dir.mkdir_p(conf.parent)
        tmp = Path["#{conf}.#{Process.pid}.tmp"]
        File.write(tmp, xml)
        File.rename(tmp, conf)
      end
      conf
    end

    def command : Array(String)
      args = [
        "-interaction=nonstopmode",
        "-halt-on-error",
        "-file-line-error",
        "-recorder",
        "-jobname=#{jobname}",
        "-output-directory=#{outdir}",
      ]
      args.concat(extra_args)
      args << input_expression
      [toolchain.executable(engine) || raise(Error.new("#{engine} is not available in #{toolchain}"))] + args
    end

    def run(stream : Bool = false) : Result
      Dir.mkdir_p(outdir)
      argv = command
      UI.debug "$ #{argv.join(' ')}"
      output = IO::Memory.new
      sink = stream ? IO::MultiWriter.new(output, STDOUT) : output
      started = Pomtex.clock
      status = Process.run(argv[0], argv[1..], env: environment, chdir: source.parent.to_s,
        input: Process::Redirect::Close, output: sink, error: sink)
      elapsed = Pomtex.clock - started

      log = File.exists?(log_path) ? File.read(log_path).scrub : output.to_s
      pdf = outdir.join("#{jobname}.pdf")
      Result.new(status.success?, status.exit_code, log, output.to_s, File.exists?(pdf) ? pdf : nil, elapsed)
    end

    # pdfTeX/LuaTeX only read pdftex.map, so map files of freshly fetched font
    # arils are added on the command line before the document is input.
    private def input_expression : String
      file = File.basename(source.to_s)
      return file if map_files.empty?
      directive = engine.starts_with?("lua") ? %q(\pdfextension mapfile) : %q(\pdfmapfile)
      return file if engine.starts_with?("xe")
      String.build do |io|
        map_files.each { |map| io << directive << "{+" << map << '}' }
        io << %q(\input{) << file << '}'
      end
    end
  end
end
