require "./config"

module Pomtex
  # Shell completions and the man page, generated from `pomtex --help` so that
  # neither can drift from the options the parser actually accepts.
  module Help
    extend self

    record Command, name : String, args : String, summary : String
    record Option, short : Char?, long : String, arg : String?, summary : String
    record Variable, name : String, summary : String

    SHELLS  = {"bash", "fish", "zsh"}
    ENGINES = {"pdflatex", "xelatex", "lualatex"}

    COMMAND_LINE  = /^\s+pomtex ([a-z]+) ?(.*?)\s{2,}(\S.*)$/
    OPTION_LINE   = /^\s+(?:-(\w)(?: \S+)?, )?--([\w-]+)(?:=(\S+))?\s{2,}(\S.*)$/
    VARIABLE_LINE = /^\s+([A-Z][A-Z_]+)\s{2,}(\S.*)$/

    def commands(help : String) : Array(Command)
      help.lines.compact_map do |line|
        line.match(COMMAND_LINE).try { |m| Command.new(m[1], m[2], m[3]) }
      end
    end

    def options(help : String) : Array(Option)
      help.lines.compact_map do |line|
        line.match(OPTION_LINE).try { |m| Option.new(m[1]?.try(&.[0]), m[2], m[3]?, m[4]) }
      end
    end

    def variables(help : String) : Array(Variable)
      section = help.partition("\nEnvironment:\n")[2]
      section.lines.compact_map do |line|
        line.match(VARIABLE_LINE).try { |m| Variable.new(m[1], m[2]) }
      end
    end

    def completion(shell : String, help : String) : String
      case shell
      when "bash" then bash(help)
      when "fish" then fish(help)
      when "zsh"  then zsh(help)
      else             raise Error.new("unknown shell: #{shell} (expected #{SHELLS.join(", ")})")
      end
    end

    # What a command's positional arguments are: .tex files, planted arils or shells.
    private def argument_kind(command : Command) : Symbol?
      case command.args
      when .includes?(".tex")  then :tex
      when .includes?("aril")  then :arils
      when .includes?("shell") then :shells
      end
    end

    private def commands_of(help : String, kind : Symbol) : Array(String)
      commands(help).select { |command| argument_kind(command) == kind }.map(&.name)
    end

    # ── fish ─────────────────────────────────────────────────────────────────

    def fish(help : String) : String
      String.build do |io|
        io << "# pomtex completions for fish (generated by `pomtex completions fish`)\n"
        io << "complete -c pomtex -f\n"
        commands(help).each do |command|
          io << "complete -c pomtex -n __fish_use_subcommand -a " << command.name
          io << " -d " << fish_quote(command.summary) << '\n'
        end
        tex = commands_of(help, :tex)
        io << "complete -c pomtex -n '__fish_use_subcommand; or __fish_seen_subcommand_from #{tex.join(' ')}'"
        # __fish_complete_suffix lists every file, .tex ones first; keep only those and directories.
        io << %q( -k -a '(__fish_complete_suffix .tex | string match -r "^.*(?:\.tex|/)(?:\t.*)?\$")') << '\n'
        commands_of(help, :arils).each do |name|
          io << "complete -c pomtex -n '__fish_seen_subcommand_from #{name}' -a '(pomtex list --names 2>/dev/null)'\n"
        end
        commands_of(help, :shells).each do |name|
          io << "complete -c pomtex -n '__fish_seen_subcommand_from #{name}' -a '#{SHELLS.join(' ')}'\n"
        end
        options(help).each do |option|
          io << "complete -c pomtex"
          option.short.try { |short| io << " -s " << short }
          io << " -l " << option.long
          case option.arg
          when "ENGINE" then io << " -x -a '" << ENGINES.join(' ') << '\''
          when "DIR"    then io << " -x -a '(__fish_complete_directories)'"
          when String   then io << " -x"
          end
          io << " -d " << fish_quote(option.summary) << '\n'
        end
      end
    end

    private def fish_quote(text : String) : String
      "'#{text.gsub('\\', "\\\\").gsub('\'', "\\'")}'"
    end

    # ── bash ─────────────────────────────────────────────────────────────────

    def bash(help : String) : String
      options = options(help)
      words = options.flat_map do |option|
        long = option.arg ? "--#{option.long}=" : "--#{option.long}"
        option.short ? ["-#{option.short}", long] : [long]
      end
      # Options whose value may follow as a separate word: `-e xelatex`.
      separate = options.select(&.arg).flat_map { |option| option.short ? ["-#{option.short}", "--#{option.long}"] : ["--#{option.long}"] }

      <<-BASH
        # pomtex completions for bash (generated by `pomtex completions bash`)
        _pomtex() {
          local cur prev cmd i
          cur="${COMP_WORDS[COMP_CWORD]}"
          prev="${COMP_WORDS[COMP_CWORD-1]}"
          local commands="#{commands(help).map(&.name).join(' ')}"
          local options="#{words.join(' ')}"

          case "$prev" in
            -e|--engine) COMPREPLY=($(compgen -W "#{ENGINES.join(' ')}" -- "$cur")); return ;;
            -o|--outdir) compopt -o filenames; COMPREPLY=($(compgen -d -- "$cur")); return ;;
            #{separate.reject { |flag| {"-e", "--engine", "-o", "--outdir"}.includes?(flag) }.join('|')}) return ;;
          esac

          case "$cur" in
            --engine=*) COMPREPLY=($(compgen -W "#{ENGINES.join(' ')}" -- "${cur#*=}")); return ;;
            --outdir=*) compopt -o filenames; COMPREPLY=($(compgen -d -- "${cur#*=}")); return ;;
            -*)
              COMPREPLY=($(compgen -W "$options" -- "$cur"))
              [[ ${COMPREPLY[0]} == *= ]] && compopt -o nospace
              return ;;
          esac

          for ((i = 1; i < COMP_CWORD; i++)); do
            case "${COMP_WORDS[i]}" in
              #{separate.join('|')}) ((i++)) ;;
              -*) ;;
              *) cmd="${COMP_WORDS[i]}"; break ;;
            esac
          done

          case "$cmd" in
            "")
              compopt -o filenames
              COMPREPLY=($(compgen -W "$commands" -- "$cur") $(compgen -f -X '!*.tex' -- "$cur") $(compgen -d -- "$cur")) ;;
            #{commands_of(help, :tex).join('|')})
              compopt -o filenames
              COMPREPLY=($(compgen -f -X '!*.tex' -- "$cur") $(compgen -d -- "$cur")) ;;
            #{commands_of(help, :arils).join('|')})
              COMPREPLY=($(compgen -W "$(pomtex list --names 2>/dev/null)" -- "$cur")) ;;
            #{commands_of(help, :shells).join('|')})
              COMPREPLY=($(compgen -W "#{SHELLS.join(' ')}" -- "$cur")) ;;
          esac
        }
        complete -F _pomtex pomtex

        BASH
    end

    # ── zsh ──────────────────────────────────────────────────────────────────

    def zsh(help : String) : String
      String.build do |io|
        io << "#compdef pomtex\n"
        io << "# pomtex completions for zsh (generated by `pomtex completions zsh`)\n\n"
        io << "_pomtex() {\n"
        io << "  local -a commands\n  commands=(\n"
        commands(help).each do |command|
          io << "    " << sh_quote("#{command.name}:#{command.summary.gsub(':', "\\:")}") << '\n'
        end
        io << "  )\n\n  local state\n  _arguments -s \\\n"
        options(help).each do |option|
          summary = "[#{option.summary.gsub(/([\[\]])/, "\\\\\\1")}]"
          action = case option.arg
                   when "ENGINE" then ":engine:(#{ENGINES.join(' ')})"
                   when "DIR"    then ":directory:_files -/"
                   when String   then ":#{option.arg.not_nil!.downcase}: "
                   else               ""
                   end
          if short = option.short
            exclusive = "(-#{short} --#{option.long})"
            forms = option.arg ? "{-#{short}+,--#{option.long}=}" : "{-#{short},--#{option.long}}"
            io << "    " << sh_quote(exclusive) << forms << sh_quote(summary + action) << " \\\n"
          else
            form = option.arg ? "--#{option.long}=" : "--#{option.long}"
            io << "    " << sh_quote(form + summary + action) << " \\\n"
          end
        end
        io << "    '1: :->command' \\\n    '*:: :->args'\n\n"
        io << "  case $state in\n"
        io << "    command)\n      _describe -t commands 'pomtex command' commands\n      _files -g '*.tex' ;;\n"
        io << "    args)\n      case $words[1] in\n"
        io << "        " << commands_of(help, :tex).join('|') << ") _files -g '*.tex' ;;\n"
        io << "        " << commands_of(help, :arils).join('|') << ") compadd -- ${(f)\"$(pomtex list --names 2>/dev/null)\"} ;;\n"
        io << "        " << commands_of(help, :shells).join('|') << ") compadd " << SHELLS.join(' ') << " ;;\n"
        io << "      esac ;;\n  esac\n}\n\n"
        io << "_pomtex \"$@\"\n"
      end
    end

    private def sh_quote(text : String) : String
      "'#{text.gsub('\'', "'\\''")}'"
    end

    # ── man page ─────────────────────────────────────────────────────────────

    def man(help : String) : String
      tagline = help.lines.first.partition(" — ")[2].rchop('.')
      String.build do |io|
        io << %(.TH POMTEX 1 "" "pomtex #{VERSION}" "User Commands"\n)
        io << ".SH NAME\npomtex \\- " << roff(tagline) << '\n'
        io << ".SH SYNOPSIS\n.B pomtex\n.I command\n.RI [ options ]\n.br\n.B pomtex\n.I file.tex\n"
        io << ".SH DESCRIPTION\n"
        io << "pomtex compiles LaTeX documents without a full TeX distribution. It uses the system TeX\n"
        io << "installation when there is one, otherwise a portable kernel (the rind), and installs the\n"
        io << "TeX Live packages (arils) a document needs on demand. Running\n.B pomtex\n.I file.tex\n"
        io << "is a shortcut for\n.BR \"pomtex build\" .\n"
        io << ".SH COMMANDS\n"
        commands(help).each do |command|
          io << ".TP\n\\fB" << command.name << "\\fR"
          io << " \\fI" << roff(command.args) << "\\fR" unless command.args.empty?
          io << '\n' << roff(command.summary) << '\n'
        end
        io << ".SH OPTIONS\n"
        options(help).each do |option|
          io << ".TP\n"
          option.short.try { |short| io << "\\fB\\-" << short << "\\fR, " }
          io << "\\fB\\-\\-" << roff(option.long) << "\\fR"
          option.arg.try { |arg| io << "=\\fI" << arg << "\\fR" }
          io << '\n' << roff(option.summary) << '\n'
        end
        unless (variables = variables(help)).empty?
          io << ".SH ENVIRONMENT\n"
          variables.each { |variable| io << ".TP\n.B " << variable.name << '\n' << roff(variable.summary) << '\n' }
        end
        io << ".SH FILES\n.TP\n.I $XDG_CACHE_HOME/pomtex\n"
        io << "The rind, planted arils and the package index (default \\fI~/.cache/pomtex\\fR).\n"
        io << ".SH SEE ALSO\n.BR pdflatex (1),\n.BR xelatex (1),\n.BR lualatex (1)\n.PP\n"
        io << "https://github.com/Huseynteymurzade28/pomtex\n"
      end
    end

    private def roff(text : String) : String
      escaped = text.gsub('\\', "\\e").gsub('-', "\\-").gsub('→', "\\(->").gsub('—', "\\(em")
      escaped.starts_with?('.') || escaped.starts_with?('\'') ? "\\&#{escaped}" : escaped
    end
  end
end
